import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import path from "path";
import { fileURLToPath, pathToFileURL } from "url";
import fs from "fs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const mainJsUrl = pathToFileURL(path.resolve(__dirname, "main.js")).href;

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const outdir = process.env.OBSIDIAN_PLUGIN_PATH || ".";

// Ensure outdir exists
if (outdir !== "." && !fs.existsSync(outdir)) {
	fs.mkdirSync(outdir, { recursive: true });
}

const copyManifest = () => {
	try {
		fs.copyFileSync("manifest.json", path.join(outdir, "manifest.json"));
		console.log("Manifest copied to", outdir);
	} catch (err) {
		console.error("Failed to copy manifest:", err);
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	alias: {
		"onnxruntime-node": path.resolve(__dirname, "onnx-shim.js"),
		"sharp": path.resolve(__dirname, "sharp-shim.js")
	},
	define: {
		"import.meta.url": JSON.stringify(mainJsUrl)
	},
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: path.join(outdir, "main.js"),
	plugins: [{
		name: 'copy-manifest',
		setup(build) {
			build.onEnd(() => {
				copyManifest();
			});
		},
	}],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
